### PR TITLE
Shrinkray/46/fix semantic html

### LINKED ISSUE #46: [A11Y] Fix Semantic HTML
## Accessibility Issue Description

Multiple layout sections are using `<header>` elements for section titles instead of proper heading tags (`<h1>`, `<h2>`, etc.). This creates an improper document outline and makes it difficult for screen readers to navigate the page structure and understand content hierarchy.

1. Inconsistent hierarchy issues
   - Headings follow no semantic pattern
    - Often `<h1>` should be lower
2. Missing page titles
3. Landmark issues
4. Navigation structure
    - Uses `<nav>` correctly but could benefit from aria-current attributes
    - Missing `aria-current="page"` for active navigation items
5. Card component issues

## WCAG Guidelines Violated

- [x] Perceivable (1.x)
- [ ] Operable (2.x)
- [x] Understandable (3.x)
- [x] Robust (4.x)

## Specific WCAG Criteria

- [ ] 1.1.1 Non-text Content
- [x] 1.3.1 Info and Relationships
- [ ] 1.4.3 Contrast (Minimum)
- [ ] 1.4.4 Resize text
- [ ] 2.1.1 Keyboard
- [ ] 2.1.2 No Keyboard Trap
- [x] 2.4.1 Bypass Blocks
- [ ] 2.4.2 Page Titled
- [ ] 2.4.3 Focus Order
- [ ] 2.4.4 Link Purpose
- [ ] 3.1.1 Language of Page
- [x] 4.1.2 Name, Role, Value
- [ ] Other (please specify):

## Steps to Reproduce

1. Go to the homepage of the DevFest website
2. Use assistive technology: Screen reader (NVDA, JAWS, VoiceOver)
3. Navigate through the page sections using heading navigation
4. Observe that section titles are not properly identified as headings in the document outline

## Expected Behavior

Section titles should be properly marked up as heading elements (`<h2>`) so that:
- Screen readers can announce them as headings
- Users can navigate between sections using heading navigation
- The document outline properly reflects the content hierarchy
- Search engines can understand the page structure

## Actual Behavior

Section titles are wrapped in `<header>` elements, which:
- Are not announced as headings by screen readers
- Cannot be navigated to using heading navigation shortcuts
- Create an improper document outline
- Make the page structure unclear to assistive technologies

## Assistive Technology Used

- [x] Screen reader (NVDA, JAWS, VoiceOver, etc.)
- [ ] Keyboard only navigation
- [ ] Voice control
- [ ] High contrast mode
- [ ] Zoom/magnification
- [ ] Other (please specify):

## Impact Level

- [ ] Critical - Prevents access to content/functionality
- [x] High - Significantly impacts user experience
- [ ] Medium - Somewhat impacts user experience
- [ ] Low - Minor impact on user experience

## Suggested Solution

Replace all `<header>` elements used for section titles with appropriate heading tags:
- Use `<h2>` for main section headings (since `<h1>` should be reserved for the page title)
- Use `<h3>` etc on down
- Maintain all existing CSS classes and styling
- Ensure proper heading hierarchy throughout the site

**Files to update:**
- `src/layouts/DevTeamSection.jsx`
- `src/layouts/SpeakersSection.jsx`
- `src/layouts/SessionsSection.jsx`
- `src/layouts/SponsorsSection.jsx`
- `src/layouts/OrganizersSection.jsx`
- `src/layouts/FacilitatorsSection.jsx`
- ~~`src/components/Navbar.jsx`~~

## Testing Environment

- **Browser**: [e.g. Chrome, Firefox, Safari]
- **Assistive Technology**: [e.g. NVDA, JAWS, VoiceOver]
- **Operating System**: [e.g. Windows, macOS, iOS, Android]

### PR DESCRIPTION
**Pull request by shrinkray**
# Pull Request

## Description

Comprehensive accessibility and semantic HTML improvements across the DevFest website. This PR addresses multiple WCAG compliance issues and enhances the user experience for all users, including those using assistive technologies.

## Type of Change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [x] Code refactoring
- [ ] Performance improvement
- [x] Accessibility improvement
- [ ] Other (please describe):

## Related Issues

Fixes #46  semantic HTML issues identified during accessibility audit
Addresses WCAG 2.1 AA compliance gaps
Improves navigation and landmark structure

## Code Quality Checklist

- [x] Code follows the project's coding standards
- [x] Self-review of the code has been performed
- [x] Code is properly commented where necessary
- [x] No console.log statements left in the code
- [x] No hardcoded values that should be configurable
- [x] Error handling is implemented where appropriate

## Testing

- [x] Changes have been tested locally
- [x] All existing tests pass (if applicable)
- [ ] New tests have been added for new functionality (if applicable)
- [x] Manual testing has been performed
- [x] Accessibility testing has been performed (for UI changes)

## Accessibility (for UI changes)

- [x] All interactive elements are keyboard accessible
- [x] Color contrast meets WCAG AA standards
- [x] Images have appropriate alt text
- [x] Form labels are properly associated
- [x] Focus indicators are visible
- [x] Screen reader compatibility has been tested

## Build & Deployment

- [x] Application builds successfully
- [x] No build warnings or errors
- [x] Dependencies are up to date
- [x] No security vulnerabilities introduced

### Locations button for directions
Screenshot 2025-09-29 at 11 43 10 AM

### Centered headings
Screenshot 2025-09-29 at 11 51 34 AM

## Additional Notes

Made a few changes that address aesthetics. 
Work on navbar was addressed on the mobile-navbar-fix branch

---

**Note**: This PR will be automatically checked for:

- Code quality (ESLint)
- Code formatting (Prettier)
- Build verification
- Accessibility compliance
- Security vulnerabilities

All checks must pass before this PR can be merged.

### CODE REVIEW

File: src/pages/Home.jsx [hunk 1]
```diff
@@ -11,7 +11,10 @@ import SponsorsSection from '@/layouts/SponsorsSection'
 
 function Home() {
   return (
-    <main>
+    <main aria-labelledby="main-heading">
```
Comment (ShugKnight24) [inline src/pages/Home.jsx]: This element was removed [here](https://github.com/GDG-Detroit/devfest-website/pull/45/files)

The accompanying change was made in PageLayout, which this will now use

**Review by ShugKnight24 — COMMENTED** [review]
This is a good PR - I think we've deviated from 2025 a too much in the PRs we have up currently. We should get things in sync before making these changes creating conflicts and potentially overwriting previous work depending on merge order

**Comment by shrinkray** [comment]
Should be up to date with branch.

File: src/components/speakers/SpeakerCard.jsx [hunk 2]
```diff
@@ -30,7 +30,13 @@ const SpeakerCard = ({
...
 
       {isModalOpen && id === speakerID && (
-        <div className="fixed inset-0 z-50 flex items-center justify-center bg-gray-800/75">
+        <div
+          className="fixed inset-0 z-50 flex items-center justify-center bg-gray-800/75"
+          role="dialog"
+          aria-modal="true"
+          aria-labelledby="speaker-modal-title"
+          aria-describedby="speaker-modal-bio"
+        >
```
Comment (ShugKnight24) [inline src/components/speakers/SpeakerCard.jsx:80]: I changed the structure of this in #42 so there might be conflicts that arise depending on which gets merged first

File: src/pages/NotFound.jsx [hunk 3]
```diff
@@ -11,18 +12,20 @@ const NotFound = () => {
...
-      </h1>
-      <p className="text-xl">
-        The page you were looking for does not exist, you will be redirected to
-        the home page in 5 seconds or you can click the link below.
-      </p>
-      <NavLink className="text-blue-500 hover:underline" to="/">
-        Return to Home Page
-      </NavLink>
-    </div>
+    <PageLayout>
```
Comment (ShugKnight24) [inline src/pages/NotFound.jsx:15]: I think wrapping this in page layout is good and keeps things consistent

If we're adding now a Navbar here, we should probably do some conditional rendering like @JustinBeaudry is doing in #30 as most of the nav is tailored for the home page

A bit of a moot point as the user will get redirected there

**Review by ShugKnight24 — COMMENTED** [review]
Good PR, addresses accessibility warnings we're currently seeing

Might have some conflicts depending on merge order & think we should address the Navbar in the future

I'll let @JustinBeaudry run his cursor bot etc

**Comment by shrinkray** [comment]
@ShugKnight24 Complete review and fixed all areas, all pass

**Review by JustinBeaudry — APPROVED** [review]
Great work @shrinkray!
